from enum import StrEnum


class ErrorCode(StrEnum):
    POST_NOT_FOUND = "POST_NOT_FOUND"
    TAG_NOT_FOUND = "TAG_NOT_FOUND"
    SLUG_CONFLICT = "SLUG_CONFLICT"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    CONTENT_NOT_FOUND = "CONTENT_NOT_FOUND"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    INTERNAL = "INTERNAL"
